export interface CampaignSuggestion {
  label: string;
  text: string;
}

export const CAMPAIGN_SUGGESTIONS: CampaignSuggestion[] = [
  { label: "🛒 Abandoned Cart Recovery - High Value", text: "Target users who abandoned carts worth over ₹2,499 in the last 48 hours with a localized urgency notification and 10% discount code." },
  { label: "🛍️ Abandoned Cart - Low Value Threshold", text: "Recover carts under ₹999 with free shipping incentives and reminder sequences across SMS and email channels." },
  { label: "⏰ Time-Based Cart Abandonment", text: "Trigger abandonment flows at 1 hour, 24 hours, and 72 hours post-abandonment with escalating discount tiers (5%, 10%, 15%)." },
  { label: "📱 Mobile Cart Abandonment", text: "Target users who abandoned on mobile devices with push notifications and simplified checkout links." },
  { label: "💳 Payment Failure Recovery", text: "Re-engage customers whose payment failed at checkout with alternative payment method suggestions and saved cart recovery links." },
  { label: "🎁 Exit Intent Cart Saver", text: "Capture users about to leave with cart contents via exit-intent popup offering same-day shipping guarantee." },
  { label: "📦 Back-in-Stock Cart Recovery", text: "Notify customers who abandoned items that are now back in stock with automatic cart restoration." },
  { label: "🏷️ Discount-Triggered Recovery", text: "Send personalized discount codes based on cart value tiers: ₹500 off on ₹5000+, ₹200 off on ₹2000+." },
  { label: "🔄 Cross-Sell Cart Recovery", text: "Recover abandoned carts by suggesting complementary products with bundle discounts." },
  { label: "💡 Rated Cart Recovery", text: "For users who rated products 4+ stars but didn't purchase - send review-to-purchase conversion flow." },
  { label: "👥 RFM Segmentation - High Value", text: "Group profiles dynamically using Recency, Frequency, Monetary telemetry matrices to isolate high-value cohorts from churn risks." },
  { label: "📊 Behavioral Segmentation", text: "Segment based on product category affinity, average session duration, pages per visit, and scroll depth metrics." },
  { label: "🎯 Lookalike Audience Expansion", text: "Build lookalike segments from top 10% spenders to acquire similar high-intent customers." },
  { label: "🏆 Tier-Based Segmentation", text: "Create dynamic segments for Bronze (0-5 orders), Silver (6-15 orders), Gold (16-30 orders), Platinum (30+ orders)." },
  { label: "🌍 Geographic Segmentation", text: "Target by city, state, region, or climate zone for localized promotions and weather-triggered campaigns." },
  { label: "📅 Lifecycle Stage Funnel", text: "Segment by journey stage: Prospect → First Purchase → Repeat Buyer → Loyalist → At-Risk → Churned." },
  { label: "💸 Predicted LTV Segmentation", text: "Use predictive scoring to segment customers by forecasted lifetime value (High: ₹50k+, Mid: ₹10-50k, Low: under ₹10k)." },
  { label: "🕒 Time-Based Cohorts", text: "Group by acquisition month, last purchase recency, purchase frequency patterns, and seasonal behavior cycles." },
  { label: "📱 Device Preference Segmentation", text: "Segment by mobile-first vs desktop-first users for optimized channel selection and creative formats." },
  { label: "🎨 Psychographic Clusters", text: "Segment by brand affinity (luxury vs value), shopping motivations (functional vs experiential), and price sensitivity." },
  { label: "💸 Win-back Lost Users Matrix", text: "Re-engage churned high-LTV customers who haven't purchased in 90+ days with personalized tier reward offers (20% off + free shipping)." },
  { label: "🔄 Dormant User Reactivation", text: "Target users inactive for 60+ days with \"We miss you\" campaigns featuring new arrivals and personalized product recommendations." },
  { label: "⏰ Graduated Win-back Sequence", text: "3-step sequence: Month 1 (10% off), Month 2 (15% off + free shipping), Month 3 (20% off + ₹500 credit)." },
  { label: "🎂 Birthday Win-back", text: "Re-engage lapsed customers on their birthday with special offers and personalized messages." },
  { label: "📊 Post-Purchase Lapse Prevention", text: "Target customers who haven't purchased within expected repurchase window with tailored recommendations." },
  { label: "🔔 App Re-engagement", text: "Re-engage users who installed app but haven't opened in 30+ days with exclusive app-only offers." },
  { label: "📧 Email Re-permissioning", text: "Win-back unengaged email subscribers with preference center updates before list cleansing." },
  { label: "⭐ Review Reactivation", text: "Re-engage customers who left positive reviews but stopped purchasing with VIP treatment offers." },
  { label: "🛍️ Seasonal Win-back", text: "Target lapsed customers before major shopping seasons with preview access." },
  { label: "🤝 Referral Reactivation", text: "Win-back customers who previously referred friends with double referral rewards for returning." },
  { label: "💎 VIP Loyalty Elevate Loop", text: "Offer exclusive early-access flash-sale passes to top 5% historical spenders to maximize lifetime metrics." },
  { label: "🏆 Platinum Tier Concierge", text: "Provide personalized shopping assistance, priority shipping, and dedicated support lines for platinum members." },
  { label: "⭐ Points Multiplier Events", text: "Run 2x/3x loyalty points campaigns for gold/platinum tiers during new collection launches." },
  { label: "🎁 Birthday Rewards Program", text: "Automatically apply birthday rewards: ₹500 credit + free shipping + double points for VIP tiers." },
  { label: "🔄 Tier Upgrade Incentives", text: "Notify customers close to next tier with personalized spend challenges." },
  { label: "👑 Founder's Circle", text: "Invite-only program for top 100 customers with exclusive previews, co-design opportunities, and annual gifts." },
  { label: "🎟️ Members-Only Flash Sales", text: "Run 24-hour flash sales exclusively for loyalty members with up to 50% off select categories." },
  { label: "📈 Milestone Rewards", text: "Celebrate customer milestones: 1st order (10% off), 10th order (free product), 25th order (₹2,500 credit)." },
  { label: "⏳ Points Expiry Prevention", text: "Notify customers before points expire with bonus point opportunities to maintain engagement." },
  { label: "⚙️ Custom Tier Benefits", text: "Let platinum members choose their benefits: free expedited shipping, gift wrapping, or donation matching." },
  { label: "🚀 New Collection Launch", text: "Coordinate multi-channel launch sequence: Teaser (7 days) → Preview (3 days) → Launch Day → Follow-up (3 days)." },
  { label: "👟 Apparel Drop Reactivation", text: "Promote upcoming minimalist apparel drops to customers with strong purchase history in streetwear vectors." },
  { label: "🎧 Pre-order Campaign", text: "Build anticipation with pre-order campaigns offering exclusive bonuses for early commitments." },
  { label: "📦 Bundle Launch", text: "Introduce product bundles with 15% discount and cross-category recommendations based on purchase history." },
  { label: "🕒 Seasonal Collection Preview", text: "Give top-tier loyalty members first access to seasonal collections 48 hours before general release." },
  { label: "📱 App-First Launch", text: "Release new products exclusively on mobile app for 24 hours before website to drive app downloads." },
  { label: "🤝 Influencer Collaboration Launch", text: "Coordinate influencer-led launches with unique discount codes and affiliate tracking per influencer." },
  { label: "🌏 Regional Launch Sequences", text: "Stagger product launches by geography to manage inventory and create localized buzz." },
  { label: "🔥 Limited Edition Drop", text: "Create scarcity with limited edition products featuring countdown timers and stock-level notifications." },
  { label: "🔄 Restock Alert Campaign", text: "Notify waitlisted customers about restocked items with 24-hour priority access." },
  { label: "📈 AOV Boost - Bundle Builder", text: "Design intelligent bundle mechanics and threshold cross-sells to uplift average basket metrics." },
  { label: "🎯 Post-Purchase Cross-sell", text: "Show complementary products in post-purchase emails with 10% off for adding to current order." },
  { label: "🛒 Cart Threshold Incentives", text: "Free shipping at ₹999, free gift at ₹1,499, 10% off at ₹2,499, 15% off at ₹3,999." },
  { label: "📉 Volume Discount Tiers", text: "Buy more, save more: Buy 2 (5% off), Buy 3 (10% off), Buy 4+ (15% off)." },
  { label: "📦 Frequently Bought Together", text: "Recommend products commonly purchased together with bundle pricing." },
  { label: "🎁 Gift with Purchase", text: "Free gift on orders over ₹2,500 with gift choices personalized based on purchase history." },
  { label: "⚙️ Progressive Profiling", text: "Collect additional customer data in exchange for increasing discount tiers during checkout." },
  { label: "🛍️ Shop the Look", text: "Promote complete outfits with \"Get the full look\" bundles at 20% off individual prices." },
  { label: "🔄 Subscription Cross-sell", text: "Convert one-time purchases to subscriptions with 15% first-month discount and free shipping." },
  { label: "⭐ Review-Driven Uplift", text: "Show products with high ratings (4.5+ stars) as alternatives to encourage higher-value purchases." },
  { label: "📱 Omnichannel Routing Optimization", text: "Evaluate engagement scores to automatically branch between WhatsApp, SMS, Email, and Push." },
  { label: "🔄 Channel Preference Learning", text: "Track response rates per channel to dynamically route to highest-performing channel." },
  { label: "📧 Email vs SMS Split Testing", text: "A/B test channel effectiveness: email for education, SMS for urgency, WhatsApp for personalization." },
  { label: "🔔 Push for Time-Sensitive", text: "Route flash sale announcements to push for app users, email for non-app users." },
  { label: "💬 WhatsApp for Concierge", text: "Use WhatsApp for high-touch interactions: order updates, VIP support, style consultations." },
  { label: "📞 SMS for Critical Alerts", text: "Send payment failures, delivery updates, and security alerts via SMS for guaranteed delivery." },
  { label: "🔁 Cross-Channel Sequences", text: "Email → (no open) SMS after 4h → (no response) WhatsApp after 24h → Push after 48h." },
  { label: "📊 Channel Attribution", text: "Track which channel drove final conversion for multi-touch campaigns." },
  { label: "🎯 Retargeting Across Channels", text: "Retarget email non-openers with SMS, then WhatsApp, then push." },
  { label: "📈 Channel Preference Survey", text: "Ask customers to set channel preferences during onboarding with 5% off incentive." },
  { label: "⏱️ Real-Time Intent Pulse Capture", text: "Listen for micro-signals: product viewing duration, category depth to update affinity tags in real-time." },
  { label: "🔄 Behavioral Event Engine", text: "Trigger campaigns on events: product view (5+), add-to-cart, price drop on wishlist." },
  { label: "📈 Live Dashboard Analytics", text: "Real-time campaign metrics: opens, clicks, conversions, revenue with <30s latency." },
  { label: "🎯 In-Session Personalization", text: "Modify on-site content and offers based on real-time browsing behavior." },
  { label: "📱 App Event Tracking", text: "Track and respond to app events: screen views, button clicks, time spent per screen." },
  { label: "🌐 Webhook Listener Configuration", text: "Configure webhooks to fire on customer actions: purchase, review, support ticket." },
  { label: "📉 Predictive Exit Intent", text: "Predict when user is about to leave based on mouse movements to trigger exit offers." },
  { label: "🎯 Dynamic Content Swapping", text: "Swap email content blocks based on real-time inventory, weather, or time-of-day." },
  { label: "📊 A/B Test Auto-Decisioning", text: "Automatically declare winners after statistical significance (95% confidence)." },
  { label: "🔄 Webhook Retry Logic", text: "Exponential backoff: retry at 1s, 5s, 30s, 5m, 1h intervals up to 24h." },
  { label: "🔄 Automated Lifecycle Triggers", text: "Configure webhook listeners to fire personalized touchpoints based on behavioral events." },
  { label: "📊 Churn Risk Scoring", text: "Score customers 0-100 on churn risk using engagement, recency, support tickets." },
  { label: "🎯 High-Risk Retention Offers", text: "Auto-deploy 25% off + free shipping to customers with churn score >80." },
  { label: "📈 Milestone Celebrations", text: "Celebrate 1 month, 6 month, 1 year anniversaries with personalized offers." },
  { label: "🔄 Reactivation for Soft Churn", text: "Target soft churn (30-60 days inactive) with product recommendations." },
  { label: "📱 App Re-engagement Push", text: "Send push notifications to app users inactive for 14+ days." },
  { label: "📧 Win-back Email Series", text: "4-part series: Week 1 (We miss you), Week 2 (New arrivals), Week 3 (15% off), Week 4 (Final)." },
  { label: "🎁 Loyalist Appreciation", text: "Surprise top 10% of customers with unexpected gifts or handwritten notes." },
  { label: "📊 NPS Promoter Activation", text: "Turn NPS promoters (9-10) into referrers with double-sided rewards." },
  { label: "🔄 Feedback Loop for Detractors", text: "Engage NPS detractors (0-6) with service recovery offers." },
  { label: "🎯 Acquisition Source Fine-Tuning", text: "Isolate customers from high-intent paid funnels to optimize onboarding workflows." },
  { label: "📱 First-Time User Onboarding", text: "Multi-step: Welcome (Day 0), Feature tour (Day 1), Incentive (Day 3), Review (Day 7)." },
  { label: "📊 Referral Program Launch", text: "Launch with ₹500 credit for referrer, ₹250 for referee, double rewards during launch week." },
  { label: "🎯 Lookalike Retargeting", text: "Retarget high-value lookalike segments with customized welcome offers." },
  { label: "📱 App Download Attribution", text: "Track and reward app downloads from email campaigns with exclusive coupons." },
  { label: "📊 Lead Scoring for Acquisitions", text: "Score leads 0-100 based on fit + engagement (opens, site visits)." },
  { label: "🎯 Paid Social Retargeting", text: "Retarget high-intent engagers with customized landing pages." },
  { label: "📧 Welcome Flow Optimization", text: "A/B test: Discount-first vs Community-first vs Education-first." },
  { label: "📊 First Purchase Acceleration", text: "Reduce time-to-first-purchase with urgency-based 24-hour discount codes." },
  { label: "🎯 Seasonal Acquisition Spikes", text: "Capture seasonal traffic: Browse abandon → Cart → Purchase sequences for holidays." },
];
