export interface DemoCustomer {
  id: string;
  name: string;
  email: string;
  totalSpend: number;
  orderCount: number;
  tier: string;
  city: string;
  lastOrderDate: string;
  preferredChannel: string;
  persona: string;
  region: string;
  phone?: string;
  tags?: string[];
  engagementScore?: number;
}

export interface DemoDataset {
  dataset: string;
  theme: string;
  desc: string;
  customers: DemoCustomer[];
}

export const DEMO_DATASETS: DemoDataset[] = [
  {
    dataset: "CODE & CHAI COLLECTIVE",
    theme: "Tech Startup + Premium Coffee",
    desc: "Bangalore, Hyderabad, Pune developers. High-end keyboards, coffee machines. Tech Enthusiasts dominate.",
    customers: [
      {
        id: "cc001",
        name: "Aditya Sharma",
        email: "aditya.debug@gitpush.dev",
        totalSpend: 185000,
        orderCount: 22,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-08",
        preferredChannel: "whatsapp",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc002",
        name: "Priya Kapoor",
        email: "priya.keyboards@script.io",
        totalSpend: 156000,
        orderCount: 19,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-12",
        preferredChannel: "whatsapp",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc003",
        name: "Rahul Patel",
        email: "rahul.standdesk@final_final.com",
        totalSpend: 98000,
        orderCount: 14,
        tier: "gold",
        city: "Hyderabad",
        lastOrderDate: "2025-01-28",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "cc004",
        name: "Vikram Singh",
        email: "vikram.coffee@codebrew.io",
        totalSpend: 142000,
        orderCount: 18,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-05",
        preferredChannel: "email",
        persona: "impulse-shopper",
        region: "south"
      },
      {
        id: "cc005",
        name: "Neha Gupta",
        email: "neha.devtools@merge.dev",
        totalSpend: 78000,
        orderCount: 11,
        tier: "gold",
        city: "Pune",
        lastOrderDate: "2025-02-10",
        preferredChannel: "sms",
        persona: "tech-enthusiast",
        region: "west"
      },
      {
        id: "cc006",
        name: "Arjun Reddy",
        email: "arjun.workspace@hyderabadtech.io",
        totalSpend: 125000,
        orderCount: 17,
        tier: "platinum",
        city: "Hyderabad",
        lastOrderDate: "2025-02-01",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "cc007",
        name: "Samantha Chen",
        email: "sam.ergonomic@pushcode.dev",
        totalSpend: 52000,
        orderCount: 8,
        tier: "silver",
        city: "Bangalore",
        lastOrderDate: "2025-01-15",
        preferredChannel: "whatsapp",
        persona: "impulse-shopper",
        region: "south"
      },
      {
        id: "cc008",
        name: "Karan Malhotra",
        email: "karan.mech.keys@startup.sh",
        totalSpend: 168000,
        orderCount: 21,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-13",
        preferredChannel: "email",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc009",
        name: "Divya Sengupta",
        email: "divya.designer@canvas.dev",
        totalSpend: 34000,
        orderCount: 5,
        tier: "bronze",
        city: "Hyderabad",
        lastOrderDate: "2025-01-08",
        preferredChannel: "sms",
        persona: "inactive-customer",
        region: "south"
      },
      {
        id: "cc010",
        name: "Mihir Thakur",
        email: "mihir.setup@workspace.io",
        totalSpend: 95000,
        orderCount: 13,
        tier: "gold",
        city: "Pune",
        lastOrderDate: "2025-02-06",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "west"
      },
      {
        id: "cc011",
        name: "Isha Pandey",
        email: "isha.cafe@coffeedev.io",
        totalSpend: 112000,
        orderCount: 16,
        tier: "gold",
        city: "Bangalore",
        lastOrderDate: "2025-02-09",
        preferredChannel: "whatsapp",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc012",
        name: "Rohan Bhattacharya",
        email: "rohan.fullstack@code.dev",
        totalSpend: 78500,
        orderCount: 10,
        tier: "gold",
        city: "Hyderabad",
        lastOrderDate: "2025-02-03",
        preferredChannel: "email",
        persona: "impulse-shopper",
        region: "south"
      },
      {
        id: "cc013",
        name: "Anjali Chopra",
        email: "anjali.monitor@screenlife.io",
        totalSpend: 131000,
        orderCount: 18,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-11",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "cc014",
        name: "Tanvi Joshi",
        email: "tanvi.code@gitflow.dev",
        totalSpend: 46000,
        orderCount: 7,
        tier: "silver",
        city: "Pune",
        lastOrderDate: "2025-01-22",
        preferredChannel: "sms",
        persona: "impulse-shopper",
        region: "west"
      },
      {
        id: "cc015",
        name: "Nikhil Verma",
        email: "nikhil.desk@standup.sh",
        totalSpend: 89000,
        orderCount: 12,
        tier: "gold",
        city: "Bangalore",
        lastOrderDate: "2025-02-07",
        preferredChannel: "whatsapp",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc016",
        name: "Pooja Sethi",
        email: "pooja.frontend@render.io",
        totalSpend: 64000,
        orderCount: 9,
        tier: "silver",
        city: "Hyderabad",
        lastOrderDate: "2025-01-30",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "cc017",
        name: "Siddharth Das",
        email: "sid.coffee.fanatic@bean.dev",
        totalSpend: 152000,
        orderCount: 20,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-14",
        preferredChannel: "email",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc018",
        name: "Meera Kapadia",
        email: "meera.ux@design.dev",
        totalSpend: 38000,
        orderCount: 6,
        tier: "bronze",
        city: "Pune",
        lastOrderDate: "2025-01-12",
        preferredChannel: "sms",
        persona: "inactive-customer",
        region: "west"
      },
      {
        id: "cc019",
        name: "Abhishek Roy",
        email: "abhishek.devops@infra.sh",
        totalSpend: 104000,
        orderCount: 14,
        tier: "gold",
        city: "Bangalore",
        lastOrderDate: "2025-02-04",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "cc020",
        name: "Ritika Nair",
        email: "ritika.setup@workspace.dev",
        totalSpend: 72000,
        orderCount: 10,
        tier: "gold",
        city: "Hyderabad",
        lastOrderDate: "2025-02-08",
        preferredChannel: "whatsapp",
        persona: "impulse-shopper",
        region: "south"
      },
      {
        id: "cc021",
        name: "Vivek Desai",
        email: "vivek.keyboard@mech.io",
        totalSpend: 88000,
        orderCount: 12,
        tier: "gold",
        city: "Pune",
        lastOrderDate: "2025-02-02",
        preferredChannel: "email",
        persona: "tech-enthusiast",
        region: "west"
      },
      {
        id: "cc022",
        name: "Shruti Mukherjee",
        email: "shruti.monitor@display.dev",
        totalSpend: 128000,
        orderCount: 17,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-10",
        preferredChannel: "whatsapp",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc023",
        name: "Akshay Tiwari",
        email: "akshay.fullsetup@complete.sh",
        totalSpend: 55000,
        orderCount: 8,
        tier: "silver",
        city: "Hyderabad",
        lastOrderDate: "2025-01-25",
        preferredChannel: "sms",
        persona: "impulse-shopper",
        region: "south"
      },
      {
        id: "cc024",
        name: "Preeti Saxena",
        email: "preeti.ergonomics@health.dev",
        totalSpend: 92000,
        orderCount: 13,
        tier: "gold",
        city: "Bangalore",
        lastOrderDate: "2025-02-09",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "cc025",
        name: "Varun Khanna",
        email: "varun.dev@code.io",
        totalSpend: 41000,
        orderCount: 6,
        tier: "bronze",
        city: "Pune",
        lastOrderDate: "2025-01-09",
        preferredChannel: "email",
        persona: "inactive-customer",
        region: "west"
      },
      {
        id: "cc026",
        name: "Nandini Iyer",
        email: "nandini.setup@startup.dev",
        totalSpend: 147000,
        orderCount: 19,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-12",
        preferredChannel: "whatsapp",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc027",
        name: "Rajesh Kumar",
        email: "rajesh.workspace@office.sh",
        totalSpend: 68000,
        orderCount: 9,
        tier: "gold",
        city: "Hyderabad",
        lastOrderDate: "2025-02-06",
        preferredChannel: "whatsapp",
        persona: "impulse-shopper",
        region: "south"
      },
      {
        id: "cc028",
        name: "Sneha Desai",
        email: "sneha.coffee@barista.dev",
        totalSpend: 82000,
        orderCount: 11,
        tier: "gold",
        city: "Bangalore",
        lastOrderDate: "2025-02-08",
        preferredChannel: "email",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "cc029",
        name: "Harshit Jain",
        email: "harshit.standup@desk.io",
        totalSpend: 175000,
        orderCount: 23,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-14",
        preferredChannel: "whatsapp",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc030",
        name: "Esha Sharma",
        email: "esha.designer@ui.dev",
        totalSpend: 51000,
        orderCount: 7,
        tier: "silver",
        city: "Pune",
        lastOrderDate: "2025-02-01",
        preferredChannel: "sms",
        persona: "impulse-shopper",
        region: "west"
      },
      {
        id: "cc031",
        name: "Sanjay Mehta",
        email: "sanjay.keyboard@type.sh",
        totalSpend: 99000,
        orderCount: 14,
        tier: "gold",
        city: "Hyderabad",
        lastOrderDate: "2025-02-07",
        preferredChannel: "email",
        persona: "tech-enthusiast",
        region: "south"
      },
      {
        id: "cc032",
        name: "Avni Kapoor",
        email: "avni.monitor@screen.dev",
        totalSpend: 138000,
        orderCount: 18,
        tier: "platinum",
        city: "Bangalore",
        lastOrderDate: "2025-02-11",
        preferredChannel: "whatsapp",
        persona: "tech-enthusiast",
        region: "south"
      }
    ]
  },
  {
    dataset: "PAWSITIVELY PREMIUM",
    theme: "Premium Pet Care + Luxury Products",
    desc: "Mumbai, Delhi, Chennai pet lovers. Luxury Buyer and Gift Shopper personas dominate.",
    customers: [
      {
        id: "pp001",
        name: "Zara Malik",
        email: "zara.petlover@fetch.life",
        totalSpend: 187000,
        orderCount: 23,
        tier: "platinum",
        city: "Mumbai",
        lastOrderDate: "2025-02-13",
        preferredChannel: "whatsapp",
        persona: "luxury-buyer",
        region: "west"
      },
      {
        id: "pp002",
        name: "Rohan Verma",
        email: "rohan.dogparent@bark.com",
        totalSpend: 156000,
        orderCount: 19,
        tier: "platinum",
        city: "Delhi",
        lastOrderDate: "2025-02-10",
        preferredChannel: "whatsapp",
        persona: "gift-shopper",
        region: "north"
      },
      {
        id: "pp003",
        name: "Neha Kapoor",
        email: "neha.paw.care@litterbox.com",
        totalSpend: 142000,
        orderCount: 17,
        tier: "platinum",
        city: "Mumbai",
        lastOrderDate: "2025-02-12",
        preferredChannel: "email",
        persona: "luxury-buyer",
        region: "west"
      },
      {
        id: "pp004",
        name: "Priya Desai",
        email: "priya.kittycare@feline.in",
        totalSpend: 98000,
        orderCount: 14,
        tier: "gold",
        city: "Chennai",
        lastOrderDate: "2025-02-08",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "pp005",
        name: "Amit Singh",
        email: "amit.petpal@puppies.io",
        totalSpend: 165000,
        orderCount: 21,
        tier: "platinum",
        city: "Delhi",
        lastOrderDate: "2025-02-14",
        preferredChannel: "whatsapp",
        persona: "gift-shopper",
        region: "north"
      },
      {
        id: "pp006",
        name: "Meera Sengupta",
        email: "meera.furry.friend@petshop.dev",
        totalSpend: 128000,
        orderCount: 16,
        tier: "platinum",
        city: "Mumbai",
        lastOrderDate: "2025-02-11",
        preferredChannel: "whatsapp",
        persona: "luxury-buyer",
        region: "west"
      },
      {
        id: "pp007",
        name: "Karthik Reddy",
        email: "karthik.doggy@puppy.life",
        totalSpend: 87000,
        orderCount: 12,
        tier: "gold",
        city: "Chennai",
        lastOrderDate: "2025-02-06",
        preferredChannel: "sms",
        persona: "impulse-shopper",
        region: "south"
      },
      {
        id: "pp008",
        name: "Anjali Patel",
        email: "anjali.petcentral@fetch.in",
        totalSpend: 76000,
        orderCount: 11,
        tier: "gold",
        city: "Mumbai",
        lastOrderDate: "2025-01-28",
        preferredChannel: "whatsapp",
        persona: "impulse-shopper",
        region: "west"
      },
      {
        id: "pp009",
        name: "Ravi Nair",
        email: "ravi.catlovers@kitten.com",
        totalSpend: 45000,
        orderCount: 6,
        tier: "bronze",
        city: "Delhi",
        lastOrderDate: "2025-01-15",
        preferredChannel: "sms",
        persona: "inactive-customer",
        region: "north"
      },
      {
        id: "pp010",
        name: "Divya Chopra",
        email: "divya.pet.lover@pawsup.io",
        totalSpend: 112000,
        orderCount: 15,
        tier: "gold",
        city: "Mumbai",
        lastOrderDate: "2025-02-09",
        preferredChannel: "whatsapp",
        persona: "gift-shopper",
        region: "west"
      },
      {
        id: "pp011",
        name: "Sanjay Gupta",
        email: "sanjay.doghouse@bark.io",
        totalSpend: 135000,
        orderCount: 18,
        tier: "platinum",
        city: "Delhi",
        lastOrderDate: "2025-02-12",
        preferredChannel: "email",
        persona: "luxury-buyer",
        region: "north"
      },
      {
        id: "pp012",
        name: "Pooja Sharma",
        email: "pooja.furry@petcare.dev",
        totalSpend: 91000,
        orderCount: 13,
        tier: "gold",
        city: "Chennai",
        lastOrderDate: "2025-02-07",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "pp013",
        name: "Vikram Patel",
        email: "vikram.pet.paradise@paws.life",
        totalSpend: 68000,
        orderCount: 9,
        tier: "gold",
        city: "Mumbai",
        lastOrderDate: "2025-01-30",
        preferredChannel: "sms",
        persona: "impulse-shopper",
        region: "west"
      },
      {
        id: "pp014",
        name: "Nisha Iyer",
        email: "nisha.kitty.kingdom@cat.in",
        totalSpend: 54000,
        orderCount: 7,
        tier: "silver",
        city: "Chennai",
        lastOrderDate: "2025-02-05",
        preferredChannel: "email",
        persona: "impulse-shopper",
        region: "south"
      },
      {
        id: "pp015",
        name: "Arjun Desai",
        email: "arjun.puppypal@doggo.dev",
        totalSpend: 124000,
        orderCount: 16,
        tier: "platinum",
        city: "Mumbai",
        lastOrderDate: "2025-02-13",
        preferredChannel: "whatsapp",
        persona: "gift-shopper",
        region: "west"
      },
      {
        id: "pp016",
        name: "Shruti Nair",
        email: "shruti.pet.central@petsmart.io",
        totalSpend: 82000,
        orderCount: 11,
        tier: "gold",
        city: "Delhi",
        lastOrderDate: "2025-02-08",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "north"
      },
      {
        id: "pp017",
        name: "Harsh Kumar",
        email: "harsh.furry.friend@fetch.dev",
        totalSpend: 148000,
        orderCount: 19,
        tier: "platinum",
        city: "Delhi",
        lastOrderDate: "2025-02-14",
        preferredChannel: "email",
        persona: "luxury-buyer",
        region: "north"
      },
      {
        id: "pp018",
        name: "Kavya Reddy",
        email: "kavya.dog.treats@bark.life",
        totalSpend: 39000,
        orderCount: 5,
        tier: "bronze",
        city: "Chennai",
        lastOrderDate: "2025-01-12",
        preferredChannel: "sms",
        persona: "inactive-customer",
        region: "south"
      },
      {
        id: "pp019",
        name: "Rahul Joshi",
        email: "rahul.petzone@puppy.in",
        totalSpend: 106000,
        orderCount: 14,
        tier: "gold",
        city: "Mumbai",
        lastOrderDate: "2025-02-10",
        preferredChannel: "whatsapp",
        persona: "gift-shopper",
        region: "west"
      },
      {
        id: "pp020",
        name: "Ritika Kapoor",
        email: "ritika.cat.lady@kitten.dev",
        totalSpend: 79000,
        orderCount: 10,
        tier: "gold",
        city: "Delhi",
        lastOrderDate: "2025-02-06",
        preferredChannel: "email",
        persona: "impulse-shopper",
        region: "north"
      },
      {
        id: "pp021",
        name: "Naveen Singh",
        email: "naveen.paw.paradise@petcare.life",
        totalSpend: 92000,
        orderCount: 12,
        tier: "gold",
        city: "Chennai",
        lastOrderDate: "2025-02-09",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "pp022",
        name: "Sneha Sharma",
        email: "sneha.furry.friend@pawsup.dev",
        totalSpend: 158000,
        orderCount: 20,
        tier: "platinum",
        city: "Mumbai",
        lastOrderDate: "2025-02-12",
        preferredChannel: "whatsapp",
        persona: "luxury-buyer",
        region: "west"
      },
      {
        id: "pp023",
        name: "Akshay Tiwari",
        email: "akshay.doggo@bark.com",
        totalSpend: 66000,
        orderCount: 9,
        tier: "gold",
        city: "Delhi",
        lastOrderDate: "2025-02-04",
        preferredChannel: "sms",
        persona: "impulse-shopper",
        region: "north"
      },
      {
        id: "pp024",
        name: "Aisha Malik",
        email: "aisha.petpal@fetch.in",
        totalSpend: 118000,
        orderCount: 15,
        tier: "gold",
        city: "Mumbai",
        lastOrderDate: "2025-02-11",
        preferredChannel: "whatsapp",
        persona: "gift-shopper",
        region: "west"
      },
      {
        id: "pp025",
        name: "Mohit Patel",
        email: "mohit.puppy.love@doggo.life",
        totalSpend: 48000,
        orderCount: 6,
        tier: "bronze",
        city: "Chennai",
        lastOrderDate: "2025-01-18",
        preferredChannel: "email",
        persona: "inactive-customer",
        region: "south"
      },
      {
        id: "pp026",
        name: "Priyanka Nair",
        email: "priyanka.kittycare@kitten.io",
        totalSpend: 146000,
        orderCount: 18,
        tier: "platinum",
        city: "Delhi",
        lastOrderDate: "2025-02-13",
        preferredChannel: "email",
        persona: "luxury-buyer",
        region: "north"
      },
      {
        id: "pp027",
        name: "Siddharth Reddy",
        email: "siddharth.petzone@paws.dev",
        totalSpend: 72000,
        orderCount: 10,
        tier: "gold",
        city: "Chennai",
        lastOrderDate: "2025-02-07",
        preferredChannel: "whatsapp",
        persona: "impulse-shopper",
        region: "south"
      },
      {
        id: "pp028",
        name: "Isha Kapoor",
        email: "isha.furry.angels@pawsup.life",
        totalSpend: 85000,
        orderCount: 11,
        tier: "gold",
        city: "Mumbai",
        lastOrderDate: "2025-02-08",
        preferredChannel: "sms",
        persona: "loyal-customer",
        region: "west"
      },
      {
        id: "pp029",
        name: "Varun Chopra",
        email: "varun.dog.paradise@bark.io",
        totalSpend: 172000,
        orderCount: 22,
        tier: "platinum",
        city: "Mumbai",
        lastOrderDate: "2025-02-14",
        preferredChannel: "whatsapp",
        persona: "gift-shopper",
        region: "west"
      },
      {
        id: "pp030",
        name: "Esha Patel",
        email: "esha.petcentral@fetch.dev",
        totalSpend: 58000,
        orderCount: 8,
        tier: "silver",
        city: "Delhi",
        lastOrderDate: "2025-02-02",
        preferredChannel: "email",
        persona: "impulse-shopper",
        region: "north"
      },
      {
        id: "pp031",
        name: "Nikhil Sharma",
        email: "nikhil.puppy.palace@doggo.dev",
        totalSpend: 101000,
        orderCount: 13,
        tier: "gold",
        city: "Chennai",
        lastOrderDate: "2025-02-09",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      }
    ]
  },
  {
    dataset: "IRON & GAINS",
    theme: "Premium Fitness + Supplements",
    desc: "Chandigarh, Kochi, Lucknow fitness culture. Fitness Freak dominates with massive spending.",
    customers: [
      {
        id: "ig001",
        name: "Vikram Singh",
        email: "vikram.gains@pr.reps",
        totalSpend: 198000,
        orderCount: 25,
        tier: "platinum",
        city: "Chandigarh",
        lastOrderDate: "2025-02-13",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "north"
      },
      {
        id: "ig002",
        name: "Anjali Verma",
        email: "anjali.fitness@track.fit",
        totalSpend: 172000,
        orderCount: 22,
        tier: "platinum",
        city: "Kochi",
        lastOrderDate: "2025-02-12",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "south"
      },
      {
        id: "ig003",
        name: "Kunal Reddy",
        email: "kunal.swole@carbload.com",
        totalSpend: 156000,
        orderCount: 20,
        tier: "platinum",
        city: "Lucknow",
        lastOrderDate: "2025-02-14",
        preferredChannel: "email",
        persona: "fitness-freak",
        region: "north"
      },
      {
        id: "ig004",
        name: "Rajesh Patel",
        email: "rajesh.gains@muscle.in",
        totalSpend: 145000,
        orderCount: 18,
        tier: "platinum",
        city: "Chandigarh",
        lastOrderDate: "2025-02-11",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "north"
      },
      {
        id: "ig005",
        name: "Priya Sharma",
        email: "priya.fit@strongwomen.io",
        totalSpend: 128000,
        orderCount: 17,
        tier: "platinum",
        city: "Kochi",
        lastOrderDate: "2025-02-10",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "south"
      },
      {
        id: "ig006",
        name: "Meera Kapoor",
        email: "meera.workout@fittrack.dev",
        totalSpend: 98000,
        orderCount: 14,
        tier: "gold",
        city: "Lucknow",
        lastOrderDate: "2025-02-08",
        preferredChannel: "sms",
        persona: "loyal-customer",
        region: "north"
      },
      {
        id: "ig007",
        name: "Karthik Nair",
        email: "karthik.pump@gym.life",
        totalSpend: 167000,
        orderCount: 21,
        tier: "platinum",
        city: "Kochi",
        lastOrderDate: "2025-02-13",
        preferredChannel: "email",
        persona: "fitness-freak",
        region: "south"
      },
      {
        id: "ig008",
        name: "Neha Desai",
        email: "neha.gains@nutrition.io",
        totalSpend: 64000,
        orderCount: 9,
        tier: "gold",
        city: "Chandigarh",
        lastOrderDate: "2025-01-25",
        preferredChannel: "whatsapp",
        persona: "discount-hunter",
        region: "north"
      },
      {
        id: "ig009",
        name: "Amit Singh",
        email: "amit.ripped@bodyweight.sh",
        totalSpend: 41000,
        orderCount: 5,
        tier: "bronze",
        city: "Lucknow",
        lastOrderDate: "2025-01-10",
        preferredChannel: "sms",
        persona: "inactive-customer",
        region: "north"
      },
      {
        id: "ig010",
        name: "Pooja Sharma",
        email: "pooja.gym.rat@fitzone.dev",
        totalSpend: 112000,
        orderCount: 15,
        tier: "gold",
        city: "Kochi",
        lastOrderDate: "2025-02-09",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "south"
      },
      {
        id: "ig011",
        name: "Sanjay Gupta",
        email: "sanjay.swole@protein.life",
        totalSpend: 138000,
        orderCount: 17,
        tier: "platinum",
        city: "Chandigarh",
        lastOrderDate: "2025-02-12",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "north"
      },
      {
        id: "ig012",
        name: "Ritika Patel",
        email: "ritika.fit.journey@track.io",
        totalSpend: 86000,
        orderCount: 12,
        tier: "gold",
        city: "Lucknow",
        lastOrderDate: "2025-02-06",
        preferredChannel: "email",
        persona: "loyal-customer",
        region: "north"
      },
      {
        id: "ig013",
        name: "Vikram Tiwari",
        email: "vikram.beast.mode@gym.dev",
        totalSpend: 74000,
        orderCount: 10,
        tier: "gold",
        city: "Kochi",
        lastOrderDate: "2025-02-04",
        preferredChannel: "sms",
        persona: "discount-hunter",
        region: "south"
      },
      {
        id: "ig014",
        name: "Nisha Iyer",
        email: "nisha.gains@carbup.in",
        totalSpend: 51000,
        orderCount: 7,
        tier: "silver",
        city: "Chandigarh",
        lastOrderDate: "2025-02-01",
        preferredChannel: "whatsapp",
        persona: "impulse-shopper",
        region: "north"
      },
      {
        id: "ig015",
        name: "Arjun Desai",
        email: "arjun.pump.king@strongfit.dev",
        totalSpend: 159000,
        orderCount: 20,
        tier: "platinum",
        city: "Kochi",
        lastOrderDate: "2025-02-14",
        preferredChannel: "email",
        persona: "fitness-freak",
        region: "south"
      },
      {
        id: "ig016",
        name: "Shruti Nair",
        email: "shruti.workout@yoga.life",
        totalSpend: 92000,
        orderCount: 13,
        tier: "gold",
        city: "Lucknow",
        lastOrderDate: "2025-02-07",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "north"
      },
      {
        id: "ig017",
        name: "Harsh Kumar",
        email: "harsh.gains.24x7@fit.io",
        totalSpend: 181000,
        orderCount: 23,
        tier: "platinum",
        city: "Chandigarh",
        lastOrderDate: "2025-02-13",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "north"
      },
      {
        id: "ig018",
        name: "Kavya Reddy",
        email: "kavya.strong.woman@strength.dev",
        totalSpend: 37000,
        orderCount: 5,
        tier: "bronze",
        city: "Kochi",
        lastOrderDate: "2025-01-14",
        preferredChannel: "sms",
        persona: "inactive-customer",
        region: "south"
      },
      {
        id: "ig019",
        name: "Rahul Joshi",
        email: "rahul.ripped@muscles.in",
        totalSpend: 108000,
        orderCount: 14,
        tier: "gold",
        city: "Chandigarh",
        lastOrderDate: "2025-02-10",
        preferredChannel: "email",
        persona: "fitness-freak",
        region: "north"
      },
      {
        id: "ig020",
        name: "Ritika Kapoor",
        email: "ritika.fit.goals@gymrat.dev",
        totalSpend: 71000,
        orderCount: 10,
        tier: "gold",
        city: "Lucknow",
        lastOrderDate: "2025-02-05",
        preferredChannel: "whatsapp",
        persona: "discount-hunter",
        region: "north"
      },
      {
        id: "ig021",
        name: "Naveen Singh",
        email: "naveen.pump.hero@fit.life",
        totalSpend: 124000,
        orderCount: 16,
        tier: "platinum",
        city: "Kochi",
        lastOrderDate: "2025-02-11",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "south"
      },
      {
        id: "ig022",
        name: "Sneha Sharma",
        email: "sneha.gains.queen@protein.io",
        totalSpend: 162000,
        orderCount: 21,
        tier: "platinum",
        city: "Chandigarh",
        lastOrderDate: "2025-02-12",
        preferredChannel: "email",
        persona: "fitness-freak",
        region: "north"
      },
      {
        id: "ig023",
        name: "Akshay Tiwari",
        email: "akshay.swole.dreams@carbup.dev",
        totalSpend: 58000,
        orderCount: 8,
        tier: "silver",
        city: "Lucknow",
        lastOrderDate: "2025-01-29",
        preferredChannel: "sms",
        persona: "impulse-shopper",
        region: "north"
      },
      {
        id: "ig024",
        name: "Aisha Malik",
        email: "aisha.fit.life@track.in",
        totalSpend: 118000,
        orderCount: 15,
        tier: "gold",
        city: "Kochi",
        lastOrderDate: "2025-02-08",
        preferredChannel: "whatsapp",
        persona: "loyal-customer",
        region: "south"
      },
      {
        id: "ig025",
        name: "Mohit Patel",
        email: "mohit.gym.beast@stronglife.dev",
        totalSpend: 45000,
        orderCount: 6,
        tier: "bronze",
        city: "Chandigarh",
        lastOrderDate: "2025-01-11",
        preferredChannel: "email",
        persona: "inactive-customer",
        region: "north"
      },
      {
        id: "ig026",
        name: "Priyanka Nair",
        email: "priyanka.fit.flex@muscle.life",
        totalSpend: 151000,
        orderCount: 19,
        tier: "platinum",
        city: "Lucknow",
        lastOrderDate: "2025-02-13",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "north"
      },
      {
        id: "ig027",
        name: "Siddharth Reddy",
        email: "siddharth.pump.life@fit.in",
        totalSpend: 79000,
        orderCount: 11,
        tier: "gold",
        city: "Kochi",
        lastOrderDate: "2025-02-09",
        preferredChannel: "email",
        persona: "discount-hunter",
        region: "south"
      },
      {
        id: "ig028",
        name: "Isha Kapoor",
        email: "isha.gains.grind@nutrition.io",
        totalSpend: 87000,
        orderCount: 12,
        tier: "gold",
        city: "Chandigarh",
        lastOrderDate: "2025-02-06",
        preferredChannel: "sms",
        persona: "loyal-customer",
        region: "north"
      },
      {
        id: "ig029",
        name: "Varun Chopra",
        email: "varun.beast.mode.24@fit.dev",
        totalSpend: 190000,
        orderCount: 24,
        tier: "platinum",
        city: "Kochi",
        lastOrderDate: "2025-02-14",
        preferredChannel: "whatsapp",
        persona: "fitness-freak",
        region: "south"
      },
      {
        id: "ig030",
        name: "Esha Patel",
        email: "esha.fit.journey@gymlife.dev",
        totalSpend: 55000,
        orderCount: 7,
        tier: "silver",
        city: "Lucknow",
        lastOrderDate: "2025-02-03",
        preferredChannel: "email",
        persona: "impulse-shopper",
        region: "north"
      }
    ]
  }
];
